# ==========================================================================
# COMPETITION MANAGEMENT SYSTEM - POWERSHELL BUILD SCRIPT (build.ps1)
# ==========================================================================

$publicDir = Join-Path $PSScriptRoot "public"
if (Test-Path $publicDir) {
    Remove-Item $publicDir -Recurse -Force
}
New-Item -ItemType Directory -Path $publicDir -Force | Out-Null

$items = @("index.html", "css", "js", "lib", "src", "manifest.json", "sw.js", "supabase_schema.sql", "vercel.json")
foreach ($item in $items) {
    $src = Join-Path $PSScriptRoot $item
    if (Test-Path $src) {
        Copy-Item -Path $src -Destination $publicDir -Recurse -Force
        Write-Host "Copied $item -> public/$item"
    }
}

# Inject environment variables into public/js/env.js if present
$supabaseUrl = $env:NEXT_PUBLIC_SUPABASE_URL
if (-not $supabaseUrl) { $supabaseUrl = $env:SUPABASE_URL }
$supabaseKey = $env:NEXT_PUBLIC_SUPABASE_ANON_KEY
if (-not $supabaseKey) { $supabaseKey = $env:SUPABASE_ANON_KEY }

if ($supabaseUrl -and $supabaseKey) {
    $envJsPath = Join-Path $publicDir "js/env.js"
    $envContent = "/* Generated by build.ps1 */`nwindow.ENV_SUPABASE_URL = `"$supabaseUrl`";`nwindow.ENV_SUPABASE_KEY = `"$supabaseKey`";`n"
    Set-Content -Path $envJsPath -Value $envContent
    Write-Host "⚡ Injected Supabase Environment Variables into public/js/env.js"
}

Write-Host "Build completed successfully! Public folder generated for Vercel deployment."
